```{r data generation, echo = FALSE, results = "hide"}
## DATA GENERATION
n <- sample(35:65,1)
mx <- runif(1, 40, 60)
my <- runif(1, 200, 280)
sx <- runif(1, 9, 12)
sy <- runif(1, 44, 50)
r <- round(runif(1, 0.5, 0.9), 2)
x <- rnorm(n, mx, sd = sx)
y <- (r * x/sx + rnorm(n, my/sy - r * mx/sx, sqrt(1 - r^2))) * sy

mx <- round(mean(x))
my <- round(mean(y))
r <- round(cor(x, y), digits = 2)
varx <- round(var(x))
vary <- round(var(y))

b <- r * sqrt(vary/varx)
a <- my - b * mx

X <- round(runif(1, -10, 10) + mx)

## QUESTION/ANSWER GENERATION
sol <- round(a + b * X, 3)
```

Question
========

Para `r n` empresas, foram registrados o número de funcionários $X$ e o montante das despesas de educação continuada $Y$ (em euros). O resumo estatístico do conjunto de dados é dado por:

|          | Variável $X$ | Variável $Y$ |
|:--------:|:------------:|:------------:|
| Média     | `r mx`       | `r my`       |
| Variância | `r varx`     | `r vary`     |

A correlação entre $X$ e $Y$ é igual a `r r`.

Estime o montante esperado de dinheiro gasto para educação continuada
por uma empresa com `r X` empregados usando regressão de mínimos quadrados.


Solution
========

Primeiramente, a linha de regressão $y_i = \beta_0 + \beta_1 x_i +
\varepsilon_i$ é determinada.  Os coeficientes de regressão são dados por:
\begin{eqnarray*}
&& \hat \beta_1 = r \cdot \frac{s_y}{s_x} = 
`r r` \cdot \sqrt{\frac{`r vary`}{`r varx`}} = `r round(b,5)`, \\
&& \hat \beta_0 = \bar y - \hat \beta_1 \cdot \bar x = 
`r my` - `r round(b,5)` \cdot `r mx` = `r round(a,5)`.
\end{eqnarray*}

O montante estimado de dinheiro gasto por uma empresa com
`r X` funcionários é, então, dado por:
\begin{eqnarray*}
\hat y = `r round(a, 5)` + `r round(b, 5)` \cdot `r X` = `r sol`.
\end{eqnarray*}

Meta-information
================
extype: num
exsolution: `r fmt(sol, 3)`
exname: Predição envolvendo regressão de mínimos quadrados de uma empresa;;
extol: 0.01
